<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html <?= /* @noEscape */ $htmlAttributes ?>>
<head <?= /* @noEscape */ $headAttributes ?>>
    <title>Sitemap HTML</title>
    <meta charset="utf-8"/>
    <meta name="title" content="Sitemap HTML"/>
    <meta name="robots" content="noindex,follow,noarchive"/>
    <meta http-equiv="Content-Language" content="en"/>
    <meta name="googlebot" content="noarchive"/>
</head>
<body <?= /* @noEscape */ $bodyAttributes ?>>
<?= /* @noEscape */ $layoutContent ?>
<br/>
</body>
</html>
